sudo: false
language: node_js
node_js:
- '5.0'
install:
  - npm install
  - gem install s3_website
script:
- npm run lint:errors
- npm run build
after_success:
- ./deploy.sh
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: D7VvuQP+rpk3w+ykJHmznG/87SoORZMMmHZks+WXXnO1RZKaOdS4h4LU0YGKEn4WYXk0rE9W2MtvqF6dD1NISl2VB3ZKw9bVf+IuE+EP0vqZXAiqcLMTxK9htBT+09TmLpJpdNSyqI/B7/CzCVuWa5Sabrh0aQP9j2b6UT2rZPM=
